fn main() {
    let mut b = cc::Build::new();
    b.include("c_src");
    b.include("c_src/libs");
    b.include("c_src/arch");
    b.include("c_src/core");
    b.file("c_src/libs/string.c");
    b.file("c_src/libs/mem.c");
    b.file("c_src/arch/linux/arch.c");
    b.file("c_src/core/pager.c");
    b.file("c_src/core/btree.c");
    b.file("c_src/core/txn.c");
    b.file("c_src/core/dump.c");
    b.file("c_src/core/debug.c");
    b.file("c_src/core/sql/parser.c");
    b.file("c_src/core/sql/exec_util.c");
    b.file("c_src/core/sql/exec_ddl.c");
    b.file("c_src/core/sql/exec_insert.c");
    b.file("c_src/core/sql/exec_select.c");
    b.file("c_src/core/sql/exec_write.c");
    b.file("c_src/core/sql/exec_stmt.c");
    b.file("c_src/core/sql/exec_query.c");
    b.file("c_src/core/sql/db.c");
    b.flag("-fPIC");
    b.flag("-O2");
    b.compile("rsc");
    println!("cargo:rerun-if-changed=c_src");
    println!("cargo:rerun-if-changed=src/lib.rs");
}
